# Generated by Django 4.1.3 on 2024-03-31 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdvapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('activated', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='cost',
            new_name='grow_time',
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('effect', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.skill')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='perk_modifier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sdvapi.perk'),
            preserve_default=False,
        ),
    ]
