# Generated by Django 4.1.3 on 2024-04-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdvapi', '0002_skill_rename_cost_item_grow_time_perk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Townie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.CharField(max_length=300)),
                ('portrait', models.CharField(max_length=300)),
                ('birth_day', models.IntegerField()),
                ('love_interest', models.BooleanField()),
                ('birth_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.season')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shopkeep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.townie'),
        ),
        migrations.CreateModel(
            name='SeasonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('description', models.TextField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.season')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_needed', to='sdvapi.item')),
                ('used_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.item')),
            ],
        ),
        migrations.CreateModel(
            name='NPCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_condition', models.TextField()),
                ('reward', models.CharField(max_length=200)),
                ('path', models.TextField()),
                ('townie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.townie')),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.bundle')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdvapi.item')),
            ],
        ),
    ]
